=== Cheponke/ITS122L-MapuaRedTrace/xml/donors.dtd
<!ELEMENT donors (donor+)>
<!ELEMENT donor (first_name, last_name, email, contact_number, blood_type, birth_date, sex, address, registration_date, status)>
<!ATTLIST donor id ID #REQUIRED>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT contact_number (#PCDATA)>
<!ELEMENT blood_type (#PCDATA)>
<!ELEMENT birth_date (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT registration_date (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== Cheponke/ITS122L-MapuaRedTrace/xml/donors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE donors SYSTEM "donors.dtd">
<donors>
  <donor id="D001">
    <first_name>Juan</first_name>
    <last_name>Dela Cruz</last_name>
    <email>jdelacruz@mymail.mapua.edu.ph</email>
    <contact_number>09171234567</contact_number>
    <blood_type>O+</blood_type>
    <birth_date>2000-04-15</birth_date>
    <sex>Male</sex>
    <address>Manila, Philippines</address>
    <registration_date>2025-01-10</registration_date>
    <status>Active</status>
  </donor>
  <donor id="D002">
    <first_name>Maria</first_name>
    <last_name>Santos</last_name>
    <email>msantos@mymail.mapua.edu.ph</email>
    <contact_number>09289876543</contact_number>
    <blood_type>A+</blood_type>
    <birth_date>2001-07-22</birth_date>
    <sex>Female</sex>
    <address>Quezon City, Philippines</address>
    <registration_date>2025-01-12</registration_date>
    <status>Active</status>
  </donor>
</donors>
